config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  resources :contacts, only: [:create]
  resources :portfolios

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :number,    :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "EspinozaBrand Contact Form",
      :to => "espinozab100@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :number, :content
  validates :name, :email, :number, :content, presence: true
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

  has_attached_file :image_main, styles: { large: "800x800", medium: "500x500>", thumb: "200x200>" }
  has_attached_file :web_image, styles: { large: "800x800", medium: "500x500>", thumb: "200x200>" }
  has_attached_file :logo_image, styles: { large: "800x800", medium: "500x500>", thumb: "200x200>" }
  has_attached_file :bc_image, styles: { large: "800x800", medium: "500x500>", thumb: "200x200>" }
  validates_attachment_content_type :image_main, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :web_image, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :logo_image, content_type: /\Aimage\/.*\z/
  validates_attachment_content_type :bc_image, content_type: /\Aimage\/.*\z/


  before_validation { bc_image.clear if @delete_image }

  def delete_image
    @delete_image ||= false
  end

  def delete_image=(value)
    @delete_image  = !value.to_i.zero?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      redirect_to(root_path, :notice => "Thank you for your message. We will get back to you as soon as possible :)")

    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    @contact = Contact.new
    @portfolio = Portfolio.all.order("created_at desc")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.message_me(@message).deliver_now
      redirect_to new_message_path, notice: "Thank you for your message."
    else
      render :new
    end

  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :number, :content)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_portfolio,  only: [:show, :edit, :update, :destroy]


  def index
    @portfolio = Portfolio.all.order("created_at desc")
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new portfolio_params

    if @portfolio.save
      redirect_to @portfolio, notice: "Awesome Brandon! That portfolio was succesfully saved!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit

  end

  def update
    if @portfolio.update portfolio_params
      redirect_to @portfolio, notice: "Ahhww Yea!!! Your portfolio was saved succesfully!"
    else
      render 'edit'
    end
  end



  def destroy
    @portfolio.destroy
    redirect_to portfolios_path
  end

  private

  def find_portfolio
    # @portfolio = portfolio.friendly.find(params[:id])
    @portfolio = Portfolio.find(params[:id])
  end

  def portfolio_params
    params.require(:portfolio).permit(:name, :about, :work_done, :delete_image, :web_description, :logo_description, :bc_description, :link, :image_main, :web_image, :logo_image, :bc_image, :slug)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def client_image
    "background: url(#{@portfolio.image_main.url}) no-repeat cover;"
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/contacts/create.html.slim
h1 Thank You For Your Message

app/views/contacts/new.html.slim
= form_for @contact do |f|
  form.col.s12.center-col
    .row
      .input-field.col.s4
        = f.text_field :name, required: true, class: "validate", id: "first_name"

        label
          | Full Name

      .input-field.col.s4
        = f.email_field :email, required: true, class: "validate"

        label data-error="wrong" data-success="right" for="email"  Email


      .input-field.col.s4
        = f.text_field :number, class: "validate"

        label
          | Phone Number
    .row
      .input-field.col.s12
        = f.text_area :message, id: "textare1", class: "materialize-textarea"

        label[for="textarea1"]
          | Message

      = f.submit 'Yes! Send It!', class: " submit-btn btn waves-effect waves-light"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | EspinozabrandCom
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    - if notice
      #notice-wrapper
        p.notice= notice
    - elsif alert
      #notice-wrapper
        p.alert= alert

    nav.navbar-fixed
      .nav-wrapper.nav-padding
        a.brand-logo[href="#"]
          img[src="/assets/logo7-2-white.png"]
        ul#nav-mobile.right.hide-on-med-and-down
          li
            a[href="sass.html"]
              | Home
          li
            a[href="badges.html"]
              | Services
          li
            a[href="collapsible.html"]
              | Portfolio
          li
            a[href="collapsible.html"]
              | Contact
    = yield

app/views/main/_about_us.html.slim
.row#about
  .container
    .col.l12.s12
      h2.center
        | About Us
      .col.s6.center-col
        .divider
      .col.s12
        p
          | Espinozabrand is formed by a group of developers from North America. We work hard to always satisfy your needs by taking in mind your thoughts and opinions. You play an important crucial role for us to deliver your business the best product possible.

app/views/main/_contact.html.slim
.row#contact
  .container
    .col.s12
      h2.center
        | Contact Us
      .col.s6.center-col
        .divider
      .col.s10.center-col
        p.center Contact us for a <b>FREE</b> quote or just say hi
      .row
        = render :template => "contacts/new"

app/views/main/_header.html.slim
header.main-header
  .container
    .row
      .col.l8.s12
          h2.left-align.white-font
            | <span>Unique</span> & <span>Modern</span> Designs for your <span class="header-bold">Business</span> = <span>Our Work</span>

app/views/main/_portfolio.html.slim
.row#portfolio
  .container
    .col.l12.s12
      h2.center
        | Our Portfolio
      .col.s6.center-col
        .divider
    .col.s12.portfolio-section
      - @portfolio.each do |portfolio|
        .col.l4.m6.s12.caption.portfolio-cols
          = link_to (image_tag portfolio.image_main.url, class: "portfolio-img"), portfolio
          .caption-overlay
            h5 = link_to portfolio.name, portfolio, class: "portfolio-title-img"
            .divider
            p = link_to portfolio.work_done, portfolio, class: "portfolio-work-img"

            = link_to "View More", portfolio, class: "btn"

app/views/main/_what_we_do.html.slim
.container#what-we-do
  .row
    .col.l12.s12
      h2.center
        | What We Do
      .col.s6.center-col
        .divider
      .col.s10.center-col
        p.center
          | Espinozabrand always serves up something distinct. We mix our creative, unique, and modern design with a taste of your own. We get all of that and add in marketing strategies + seo.


// Responsive Web Design

.row.icons.grey-serv-bg
  .col.s10.center-col
    .col.l6.s12
      .col.l6.s8.center-col
        img.service-icon[src="assets/responsive-web-design.png"]
    .col.l6.s12
        h4.left-align
          | Responsive Web Design
        p.left-align
          | The websites we develop are completely responsive, meaning they automatically respond to any screen they are viewed on.


// Web Development

.row.icons.white-serv-bg
  .col.s10.center-col.hide-on-med-and-down
    .col.s6
      h4.left-align
        | Web Development
      p.left-align
        | Espinozabrand's experienced development team takes the time to understand your business, and finds the smartest path towards your goals.
    .col.s6
      .col.s6.center-col
        img.service-icon[src="assets/web-development-mint.png"]

  .col.s10.center-col.hide-on-large-only
    .col.l6.s12
      .col.l6.s8.center-col
        img.service-icon[src="assets/web-development-mint.png"]
    .col.l6.s12

      h4.left-align
        | Web Development
      p.left-align
        | Espinozabrand's experienced development team takes the time to understand your business, and finds the smartest path towards your goals.


// SEO

.row.icons.grey-serv-bg
  .col.s10.center-col
    .col.l6.s12
      .col.l6.s8.center-col[style="padding-top: 2vh;"]
        img.service-icon[src="assets/seo-mint.png"]
    .col.l6.s12
      h4.left-align
        | SEO
      p.left-align
        |  We want to help your business by developing a strategy that will get you to the top of those local and nationwide rankings or ultimately improving your brand.



.row.icons.white-serv-bg
  .col.s10.center-col.hide-on-med-and-down
    .col.s6
      h4.left-align
        | Branding
      p.left-align
        | We provide a full range of branding services as well as marketing design. Brand recognition is the driving force behind successful businesses.
    .col.s6
      .col.s6.center-col
        img.service-icon[src="assets/graphic-design-mint.png"]

  .col.s10.center-col.hide-on-large-only
    .col.l6.s12
      .col.l6.s8.center-col
        img.service-icon[src="assets/graphic-design-mint.png"]
    .col.l6.s12
      h4.left-align
        | Branding
      p.left-align
        | We provide a full range of branding services as well as marketing design. Brand recognition is the driving force behind successful businesses.

app/views/main/index.html.slim
= render :partial => "main/header"

= render :partial => "main/about_us"

= render :partial => "main/what_we_do"

= render :partial => "main/portfolio"
= render :partial => "main/contact"

app/views/messages/_new.html.erb
<div class="row">
  <form class="col s12 center-col">
    <%= form_for @message do |f| %>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
          </h2>

          <ul>
            <% @message.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          <ul>
        </div>
      <% end %>

      <div class="row">
        <div class="input-field col s4">
          <%= f.text_field :name %>
          <label>Full Name</label>
        </div>

        <div class="input-field col s4">
          <%= f.text_field :email %>
          <label data-error="wrong" data-success="right">Email</label>
        </div>

        <div class="input-field col s4">
          <%= f.text_field :number %>
          <label data-error="wrong" data-success="right">Phone Number</label>
        </div>
      </div>
      <div class="row">
        <div class="iput-field col s12">
          <textarea id="textarea1" class="materialize-textarea"></textarea>
          <label for="textarea1">Textarea</label>
        </div>
      </div>
      <%= f.submit 'Send', class: 'btn waves-effect waves-light'%>
    <% end %>
  </form>
</div>

app/views/messages/new.html.erb
<div class="row">
  <form class="col s12 center-col">
    <%= form_for @message do |f| %>
      <% if @message.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
          </h2>

          <ul>
            <% @message.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          <ul>
        </div>
      <% end %>

      <div class="row">
        <div class="input-field col s4">
          <%= f.text_field :name %>
          <label>Full Name</label>
        </div>

        <div class="input-field col s4">
          <%= f.text_field :email %>
          <label data-error="wrong" data-success="right">Email</label>
        </div>

        <div class="input-field col s4">
          <%= f.text_field :number %>
          <label data-error="wrong" data-success="right">Phone Number</label>
        </div>
      </div>
      <div class="row">
        <div class="iput-field col s12">
          <textarea id="textarea1" class="materialize-textarea"></textarea>
          <label for="textarea1">Textarea</label>
        </div>
      </div>
      <%= f.submit 'Send', class: 'btn waves-effect waves-light'%>
    <% end %>
  </form>
</div>

app/views/portfolios/_form.html.slim
= form_for @portfolio, html: {multipart: true} do |f|
  - if @portfolio.errors.any?
    h2
      = pluralize(@portfolio.errors.count, "error")
      |  prevented this project from saving:
    ul
      - @portfolio.errors.full_messages.each do |msg|
        li
          = msg
  .row
    .input-field.col.s4
      = f.text_field :name, required: true, class: "validate"

      label
        | Project Name

    .input-field.col.s4
      = f.text_field :work_done, class: "validate"

      label
        | Small Description

    .input-field.col.s4
      = f.text_field :link, class: "validate"

      label
        | Link



  .row
    .input-field.col.s3
      .file-field.input-field
        .btn
          span
            | Main Img
        - if @portfolio.image_main.exists?
          = image_tag @portfolio.image_main.url(:thumb)
          br
          = f.file_field :image_main, class: "validate"
        - else
          = f.file_field :image_main, class: "validate"

        .file-path-wrapper
          input.file-path.validate[type="text"]


    .input-field.col.s3
      .file-field.input-field
        .btn
          span
            | Web Img
        - if @portfolio.web_image.exists?
          = image_tag @portfolio.web_image.url(:thumb)
        - else
          = f.file_field :web_image, class: "validate"

        .file-path-wrapper
          input.file-path.validate[type="text"]

    .input-field.col.s3
      .file-field.input-field
        .btn
          span
            | Logo Img
        - if @portfolio.logo_image.exists?
          = image_tag @portfolio.logo_image.url(:thumb)
          br
          = f.file_field :logo_image, class: "validate"
        - else
          = f.file_field :logo_image, class: "validate"

        .file-path-wrapper
          input.file-path.validate[type="text"]

    .input-field.col.s3
      .file-field.input-field
        .btn
          span
            | BC Img
        - if @portfolio.bc_image.exists?
          = image_tag @portfolio.bc_image.url(:thumb)
          br
          br
          br
          = f.check_box :delete_image, :label => 'Delete Image', class: "checkboxes"
        - else
          = f.file_field :bc_image, class: "validate"

        .file-path-wrapper
          input.file-path.validate[type="text"]











  .row
    .input-field.col.s6
      = f.text_area :about, class: "materialize-textarea"

      label
        | About Client

    .input-field.col.s6
      = f.text_area :web_description, class: "materialize-textarea"

      label
        | Web Description

  .row
    .input-field.col.s6
      = f.text_area :logo_description, class: "materialize-textarea"

      label
        | Logo Description
    .input-field.col.s6
      = f.text_area :bc_description, class: "materialize-textarea"

      label
        | Business Card Description




    .col.s4
      = f.submit 'Add Project', class: " submit-btn btn waves-effect waves-light"

app/views/portfolios/edit.html.slim
.container
  .row
    .col.s12
      h3 Edit a Project from Portfolio

    .col.s12.col-center
      = render 'form'

app/views/portfolios/index.html.slim
.row#portfolio[style= "margin-top:-100px; padding-top:15%;"]
  .container
    .col.l12.s12
      h2.center
        | Our Portfolio
      .col.s6.center-col
        .divider
    .col.s12.portfolio-section
      - @portfolio.each do |portfolio|
        .col.l4.m6.s12.caption.portfolio-cols
          = link_to (image_tag portfolio.image_main.url, class: "portfolio-img"), portfolio
          .caption-overlay
            h5 = link_to portfolio.name, portfolio, class: "portfolio-title-img"
            .divider
            p = link_to portfolio.work_done, portfolio, class: "portfolio-work-img"

            = link_to "View More", portfolio, class: "btn"

app/views/portfolios/new.html.slim
.container
  .row
    .col.s12
      h3 Add New Project to Portfolio

    .col.s12.col-center
      = render 'form'

app/views/portfolios/show.html.slim
.main-div
  header.show-header[style="background-image: url('#{@portfolio.image_main.url}'); " data-adaptive-background="1" data-ab-css-background ]
    .header-text.col.s8.center-col
      h2.font-color
        = @portfolio.name

  .row
    .col.s12.center-col.portfolio-info[style="background-attachment: fixed;"]
      .row
        .col.s12.about
          .col.l6.center-col
            h4.center
              = @portfolio.name

            p.center
              = @portfolio.about

      //if statement for first section If web_image exists then show elsif bc_image exists and web_image !exists then show bc content

      - if @portfolio.web_image.exists?
        .row.white
          .col.s12.web
            .col.l6.s12
              img[src=@portfolio.web_image]
            .col.l6.s12.font-color
              h4
                | Web Design and Development
              p
                = @portfolio.web_description


      - elsif @portfolio.bc_image.exists?
        .row.dynamic-row
          .col.s12.bc[data-ab-parent]
            .col.l6.s12
              img[src=@portfolio.bc_image]
            .col.l6.s12.font-color
              h4
                | Business Card Design
              p
                = @portfolio.bc_description




      // if web_image is empty and bc_image exists display none because bc_image is already being called on the if statement above.
      - if @portfolio.web_image.blank? && @portfolio.bc_image.exists?
        .row[style="display:none;"]
      // elsif bc_imageis empty then show logo_image but first check if it is empty and if it is then display none, if not then display
      - elsif @portfolio.bc_image.blank?
        - if @portfolio.logo_image.blank?
          .row[style="display:none;"]

        - else

          .row.white
            .col.s12.logo[data-ab-parent]
              .col.l6.s12
                h4
                  | Logo Design
                p[style="color:#000;"]
                  = @portfolio.logo_description
              .col.l6.s12
                img[src=@portfolio.logo_image]

      // elsif bc_image exists then show it
      - elsif @portfolio.bc_image.exists?
        .row.white
          .col.s12.bc-white
            .col.l6.s12
              h4
                | Business Card Design
              p
                = @portfolio.bc_description
            .col.l6.s12
              img[src=@portfolio.bc_image]

      // If bc exists and logo exists then show logo and not bc because its already being called above
      - if @portfolio.bc_image.exists? && @portfolio.logo_image.exists?

        .row.white
          .col.s12.logo
            .col.l6.s12
              img[src=@portfolio.logo_image]
            .col.l6.s12
              h4
                | Logo Design
              p
                = @portfolio.logo_description

      // if logo is empty then display none
      - if @portfolio.logo_image.blank?
        .row[style="display:none;"]

br

= link_to 'Edit', edit_portfolio_path(@portfolio), class: "btn"

br

= link_to 'Back', portfolios_path, class: "btn"

br

= link_to "Delete", portfolio_path(@portfolio), method: :delete, data: { confirm: "Are you sure you want to delete this Client?"}, class: "btn"

javascript:



  $(document).ready(function(){
    $.adaptiveBackground.run();
  });